[build]
  command = "npm run build"
  publish = "radio-station-showcase-fixed/public"
  functions = "netlify-functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200